Enhance VideoInputOption on Windows: …
vignetteapp/SeeShark pull request #34
Opened 2022-09-27 15:07 UTC by ChristopheI

Get VCodec (h264 and mjpeg) or InputFormat (pixel format in fact)

Fix also how FrameRate is set

Related to issue #33

2022-09-27 15:49 UTC, Speykious requested changes

2022-09-27 15:49 UTC, Speykious commented on SeeShark/Utils/DShowUtils.cs
> -                            options.Clear();
About this line, I'm not even sure why it was here in the code examples I found, but I'm even less sure of why it shouldn't be here.
Given your current code that seems to work, can you try putting this line again and see what happens?

2022-09-27 15:49 UTC, Speykious commented on SeeShark/Utils/DShowUtils.cs
> +                            Framerate = ffmpeg.av_d2q((double)10_000_000L / v.AvgTimePerFrame, (int)10_000_000L),
Good function, I didn't know about it :+1:

2022-09-27 15:49 UTC, Speykious commented on SeeShark/Utils/DShowUtils.cs
> +                                }
I'll probably put that code in a separate method. I'll see what I can do

2022-09-27 15:49 UTC, Speykious commented on SeeShark/VideoInputOptions.cs
> +        public string? VCodec { get; set; }
It seems that you always specify _either_ the `vcodec` or the `pixel_format`. We can probably avoid putting a separate field for the `vcodec` in this case, I'd rather have SeeShark deal with that automatically in code to not complicate the API.

2022-09-28 06:41 UTC, ChristopheI commented on SeeShark/Utils/DShowUtils.cs
> -                            options.Clear();
When used I have this output for my second webcam: 
![image](https://user-images.githubusercontent.com/47391779/192706229-cbd9a24d-147d-47b2-8d6c-462b7d44b365.png)

So less results 16 instead 52: see here https://github.com/vignetteapp/SeeShark/issues/33#issuecomment-1259635656

2022-09-28 06:44 UTC, ChristopheI commented on SeeShark/VideoInputOptions.cs
> +        public string? VCodec { get; set; }
Correct. 
Perhaps **pixel_format** could be used like this (on windows)
- pixel_format => yuyv422, rgb24 , ... (so the pixel format name)
- pixel_format => vcodec=mjpeg, vcodec=h264 (so the video format with "vcodec" as prefix

2022-10-29 00:26 UTC, Speykious approved these changes
It's time we finish #30

2022-10-29 00:26 UTC, merged