Use a `Disposable` abstract class
vignetteapp/SeeShark pull request #5
Opened 2021-12-14 12:04 UTC by Speykious

In this PR, I made a `Disposable` abstract class to be used in place of `IDisposable` when the target class has nothing else to inherit.
It turned out to be much cleaner and way less repetitive, and the code has no class implementing `IDisposable` left since all the target classes had nothing to inherit.

I made it as a PR to get feedback on this idea. Do you think that making such a `Disposable` abstract class is still respecting the .NET standard, given that it is made so that the underlying code is what they recommend to write?

Regardless, I found no memory leak after this refactoring and everything works as expected.

2021-12-14 12:13 UTC, adryzz commented
hmm i mean i don't really like it much but if it cleans up the code then i guess it's fine

2021-12-15 00:07 UTC, sr229 requested changes
I don't really like the syntax of this change, it just adds more clutter and this is definitely not a change I would go for. I don't see why would you need a derived `Disposable` abstract class if `IDisposable` handles it already?

2021-12-15 00:13 UTC, Speykious commented
Because `IDisposable` doesn't actually handle some of the important stuff, like the `private void dispose(bool)` method that is always going to be the same, the destructor which is always going to call `dispose(false)`, and the `Disposed` property. I didn't know it was best practice to do all of this code for every `IDisposable`-implementing class until I read it from the corresponding .NET standard page. But the way I made a `Disposable` abstract class here makes it clear what I have to do, and turned out to be usable for all my `IDisposable` classes since they didn't inherit anything else that wasn't `IDisposable`.

What potential clutter are you afraid of though?

2021-12-15 00:18 UTC, sr229 commented
> Because `IDisposable` doesn't actually handle some of the important stuff, like the `private void dispose(bool)` method that is always going to be the same, the destructor which is always going to call `dispose(false)`, and the `Disposed` property. I didn't know it was best practice to do all of this code for every `IDisposable`-implementing class until I read it from the corresponding .NET standard page. But the way I made a `Disposable` abstract class here makes it clear what I have to do, and turned out to be usable for all my `IDisposable` classes since they didn't inherit anything else that wasn't `IDisposable`.
> 
> What potential clutter are you afraid of though?

Definitely not clutter but the way you handled the syntax. If you want a cleaner example, then I suggest taking a look how `DisposableObjects`s were done in Akihabara.

2021-12-15 00:20 UTC, sr229 requested changes

2021-12-15 00:20 UTC, sr229 commented on SeeShark/Disposable.cs
> +        protected abstract void FreeUnmanaged();
Keep the calling convention consistent. Call it `DisposeUnmanaged`.
```suggestion
        protected abstract void DisposeUnmanaged();
```

2021-12-15 00:24 UTC, Speykious commented on SeeShark/Disposable.cs
> +        protected abstract void FreeUnmanaged();
This is actually intended to call it `FreeUnmanaged` and not `DisposeUnmanaged`. This function is supposed to handle the *freeing* (and not *disposal*) of unmanaged resources. The main difference is that we can dispose of a resource as much as we want, but we cannot free a resource more than once. Any object that implements `IDisposable` would actually be disposed in `DisposeManaged()`, and only unmanaged resources like raw pointers would be freed in `FreeUnmanaged()`.

Do you think it will still cause confusion given this nuance?

2021-12-15 00:26 UTC, sr229 commented on SeeShark/Disposable.cs
> +        protected abstract void FreeUnmanaged();
the .NET convention regarding freeing up memory in the runtime is called object disposal, hence we use the `DisposeUnmanaged`, `Dispose` definitions instead. Please keep everything consistent as accordance to how the .NET classes are done please, don't do your own thing for this kinds of things.

2021-12-15 00:28 UTC, Speykious commented on SeeShark/Disposable.cs
> +        protected abstract void FreeUnmanaged();
Ah don't worry, I don't want to do things my own way here. The whole reason I made this class was so that I could actually make sure that I follow the .NET standard. Thanks, I'm gonna look it up - maybe I misread stuff about disposal.

2021-12-15 00:52 UTC, Speykious commented on SeeShark/Disposable.cs
> +        protected abstract void FreeUnmanaged();
`Dispose` instead of `Free` isn't that bad anyway, I just thought that it would have been nice to have this explicit distinction. But after some discussion, I decided that I was going to favor continuity over precise vocabulary.

2021-12-15 00:58 UTC, merged